#!/usr/bin/env bash

# Stop the Apache service if it's running
service apache2 stop

# Change the user in the nginx.conf file
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Update the default site configuration to listen on port 8080
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default

# Change the permissions of the nginx.conf file
chmod 644 /etc/nginx/nginx.conf

# Start the Nginx service
service nginx start
